apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: webserver
    image: hello-world-webserver
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80 # The port the container exposes
